### ISSUE TITLE
Custom agent size support in terraform

### ISSUE THREAD

**Issue by GraysonWu** [akuity/terraform-provider-akp#259]
Hi there, 

I'm wondering how can I use custom size of agent with terraform?

In your doc: https://registry.terraform.io/providers/akuity/akp/latest/docs/resources/cluster#nested-schema-for-specdata, it looks like it can only be one of small, medium or large, while on UI we could have custom size. 
<img width="773" alt="image" src="https://github.com/user-attachments/assets/313a2372-efe5-46f8-a592-db5f4079e842">

Thanks!

**Comment by hanxiaop** [comment]
This is not currently supported. I will work on this.
